kind: pipeline
name: testing-amd64-drone
type: docker

workspace: 
  path: /app

trigger:
  event: 
    - push
    - pull_request
steps:
  - name: List all files
    pull: always
    image: drone/git
    commands:
      - find "$PWD" | grep -v .git
  - name: zip file
    image: lunagod/drone-zip
    settings:
      input: 
        - test/**/*
      output: test1.zip
  - name: zip js file
    image: lunagod/drone-zip
    settings:
      input: 
        - test/**/*.js
      output: test-js.zip
  - name: zip txt file
    image: lunagod/drone-zip
    settings:
      input: 
        - test/**/*.js
      output: test-txt.zip
  - name: List all files
    image: drone/git
    commands:
      - find "$PWD" | grep -v .git