name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Go Test
        run: go test -v --count=1
      - name: Build test
        run: env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o release/drone-zip-release